#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : require

//#include "qef.glsl"

#define WIDTH 3200
#define HEIGHT 2400
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1 ) in;

struct Pixel{
  vec4 value;
};

layout(std140, binding = 0) buffer buf
{
    Pixel imageData[];
};

layout(std140, binding = 1) uniform ComputeUniform 
{
    vec4 uniform_value;
};

void main() 
{
    vec4 color = 
        vec4(
            gl_GlobalInvocationID.x + 1,
            gl_GlobalInvocationID.y + 1,
            gl_GlobalInvocationID.z + 1,
            length(uniform_value)
        );

    // store the rendered mandelbrot set into a storage buffer:
    imageData[gl_NumWorkGroups.x * gl_NumWorkGroups.y * gl_GlobalInvocationID.z + gl_NumWorkGroups.x * gl_GlobalInvocationID.y + gl_GlobalInvocationID.x].value = color;
}